# Generated by Django 4.2.7 on 2023-12-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniGuardian', '0002_remove_userprofile_raw_lor_userprofile_raw_lor1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_detection_score',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hightlight',
            field=models.TextField(default=''),
        ),
    ]
